check-for-updates: true
spawn:
  teleport-on-join: true
  world: ''
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
scoreboard:
  title: "&2&lSuper&a&lKitPvP"
  lines:
    - ''
    - '&2Stats:'
    - '&a Kills:&f %user-kills%'
    - '&a Deaths:&f %user-deaths%'
    - '&a KD Ratio:&f %user-kd-ratio%'
    - '&a Points:&f %user-points% ✪'
    - ''
    - '&fplay.superkitpvp.net'